// <auto-generated />
using System;
using DATA;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DATA.Migrations
{
    [DbContext(typeof(ApplicationDbContextCore))]
    partial class ApplicationDbContextCoreModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.0-preview3-35497")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MODELS.Car", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("CarId")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Brand");

                    b.Property<string>("BuildNo")
                        .HasMaxLength(30);

                    b.Property<string>("Color")
                        .HasMaxLength(30);

                    b.Property<DateTime>("Created");

                    b.Property<DateTime?>("Deleted");

                    b.Property<string>("PlateNo")
                        .IsRequired()
                        .HasMaxLength(30);

                    b.Property<decimal>("Price");

                    b.Property<DateTime?>("Updated");

                    b.HasKey("Id");

                    b.HasAlternateKey("PlateNo");

                    b.HasIndex("BuildNo")
                        .IsUnique()
                        .HasName("UX_Car_BuildNo")
                        .HasFilter("[BuildNo] IS NOT NULL");

                    b.HasIndex("Id")
                        .HasName("IX_Car_CarId");

                    b.HasIndex("PlateNo")
                        .IsUnique()
                        .HasName("UX_Car_PlateNo");

                    b.ToTable("Car");
                });
#pragma warning restore 612, 618
        }
    }
}
