SELECT 'ALTER TABLE ' + TABLE_SCHEMA + '.' + TABLE_NAME + CHAR(13) + CHAR(10) + 
	   ' ADD CONSTRAINT DFLT' + TABLE_SCHEMA + '_' + TABLE_NAME + '_' + 
	   COLUMN_NAME + CHAR(13) + CHAR(10) + 
	   ' DEFAULT (SYSDATETIME()) FOR ' + COLUMN_NAME + ';'
FROM  INFORMATION_SCHEMA.COLUMNS
WHERE COLUMN_NAME IN ('RowCreateTime', 'RowLastUpdateTime')
	 AND TABLE_SCHEMA IN ('Messages','Attendees') 
ORDER BY TABLE_SCHEMA, TABLE_NAME, COLUMN_NAME;